apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: verify-enterprise-contract-task-v01-alpha
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: verify-enterprise-contract-task-v01-alpha
    app.kubernetes.io/part-of: ec-v01-alpha
  name: verify-enterprise-contract-task-v01-alpha
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: verify-enterprise-contract-task-v01-alpha
status:
  loadBalancer: {}
