apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cli-v01-alpha
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cli-v01-alpha
    app.kubernetes.io/part-of: ec-v01-alpha
  name: cli-v01-alpha
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cli-v01-alpha
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cli-v01-alpha
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v01-alpha/cli-v01-alpha@sha256:6bb817407bd35272f7da20d6d4f2a7fe3262f122295e0753d2719bf18b06dd39
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
