apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cli-v01-alpha
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cli-v01-alpha
    app.kubernetes.io/part-of: ec-v01-alpha
  name: cli-v01-alpha
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: cli-v01-alpha
status:
  loadBalancer: {}
