apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-v01-alpha
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v01-alpha/cli-v01-alpha@sha256:c3b376bf4f9f45f83923a501a0188ff2446bab8671732de7f7f20875eb6d9f1a
        name: container-image
        resources: {}
status: {}
