apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-v01-alpha
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v01-alpha/cli-v01-alpha@sha256:32c33fc2a1c964e91a8a583843dbba6a057d5387254b6eefdaccb29412479fae
        name: container-image
        resources: {}
status: {}
