apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-v01-alpha
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v01-alpha/cli-v01-alpha@sha256:bdb71ce07aa58bac141859e80c861eec0df7280d828f7b611776bd9693dc5c6f
        name: container-image
        resources: {}
status: {}
